// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ2C0ceMyD1dEZ4_wRtw6tDpZW36-1_XE',
    appId: '1:115210430339:web:a6787bc68e1c127f1078b6',
    messagingSenderId: '115210430339',
    projectId: 'e3trafatk',
    authDomain: 'e3trafatk.firebaseapp.com',
    storageBucket: 'e3trafatk.appspot.com',
    measurementId: 'G-902JP3NMM0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPzlZyW0RL-5G46XCHlg4AaRTaTVpB3ls',
    appId: '1:115210430339:android:9fc0b0b7722e20bd1078b6',
    messagingSenderId: '115210430339',
    projectId: 'e3trafatk',
    storageBucket: 'e3trafatk.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwCGEaU6e6vhKXW3UawymJrZLfVlo2NvY',
    appId: '1:115210430339:ios:c483b504fd061ec61078b6',
    messagingSenderId: '115210430339',
    projectId: 'e3trafatk',
    storageBucket: 'e3trafatk.appspot.com',
    iosBundleId: 'com.attia.frPhilopater',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwCGEaU6e6vhKXW3UawymJrZLfVlo2NvY',
    appId: '1:115210430339:ios:c483b504fd061ec61078b6',
    messagingSenderId: '115210430339',
    projectId: 'e3trafatk',
    storageBucket: 'e3trafatk.appspot.com',
    iosBundleId: 'com.attia.frPhilopater',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQ2C0ceMyD1dEZ4_wRtw6tDpZW36-1_XE',
    appId: '1:115210430339:web:100cf4a2b5b36ea31078b6',
    messagingSenderId: '115210430339',
    projectId: 'e3trafatk',
    authDomain: 'e3trafatk.firebaseapp.com',
    storageBucket: 'e3trafatk.appspot.com',
    measurementId: 'G-6G6837DGGW',
  );
}
